# Generated by Django 2.2.3 on 2019-08-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=11)),
                ('img', models.CharField(default='default.png', max_length=200)),
                ('user_token', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
