# Generated by Django 2.2.3 on 2019-08-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190827_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='individualResume',
            field=models.CharField(default='这个人很害羞，没有留点信息', max_length=200),
        ),
    ]
