# Generated by Django 2.2.3 on 2019-08-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190829_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='birthday',
        ),
    ]
