# Generated by Django 2.2.3 on 2019-09-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190829_2101'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSold', models.BooleanField(default=False)),
                ('num', models.IntegerField(default=0)),
                ('sum', models.CharField(default=0, max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myapp.User')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.Goods')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
