# Generated by Django 2.2.3 on 2019-09-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createTime',
            field=models.DateTimeField(null=True),
        ),
    ]
