# Generated by Django 2.2.3 on 2019-09-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190909_1521'),
        ('market', '0003_order_createtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '货物', 'verbose_name_plural': '货物类'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单类'},
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSold', models.BooleanField(default=False)),
                ('num', models.IntegerField(default=0)),
                ('sum', models.CharField(default=0, max_length=20)),
                ('createTime', models.DateTimeField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='myapp.User')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='market.Goods')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车类',
                'db_table': 'carts',
            },
        ),
    ]
