# Generated by Django 2.2.3 on 2019-08-28 01:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyWord',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='mainimg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
