# Generated by Django 2.2.3 on 2019-08-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190828_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
