# Generated by Django 2.2.3 on 2019-08-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
