# Generated by Django 2.2.3 on 2019-08-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_isdelete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pk']},
        ),
    ]
