# Generated by Django 2.2.3 on 2019-09-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190830_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='PV',
            field=models.IntegerField(default=0),
        ),
    ]
