# Generated by Django 2.2.3 on 2019-09-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_pv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pk'], 'verbose_name': '文章', 'verbose_name_plural': '文章类'},
        ),
    ]
